name: 'Upload a Build Artifact to Azure Blob Storage'
description: 'Upload a build artifact that ca be used by subsequent workflow steps to Azure Blob Storage'
author: 'fixpoint'
branding:
  icon: 'sunrise'
  color: 'gray-dark'
inputs:
  connection-string:
    description: 'Connection string'
    required: true
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Directory containing files to upload'
    required: true
  container:
    description: 'Container name'
    required: false
    default: 'github-action-artifacts'
  cleanup:
    description: 'Remove all blobs under the target blob (use "true" to enable this option)'
    required: false
    default: 'true'
  extra_args:
    description: "Extra arguments that can be passed to `az storage blob upload-batch|sync`. Useful for passing flags like `--pattern` or `--destination-path`"
    required: false
  sync:
    description: "Use `az storage blob sync` to synchronize blobs recursively"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
